name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run build --if-present

  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
    - name: Copy files
      working-directory: build
      run: cp -r . /var/www/dominik.codeshape.de/prod
    - name: Check pwd
      run: pwd
